---
# Defines deployment design and assigns role to server groups

- hosts: mons
  become: True
  roles:
  - ceph-mon

- hosts: osds
  become: True
  roles:
  - ceph-osd

- hosts: mdss
  become: True
  roles:
  - ceph-mds

- hosts: mons
  serial: 1
  tasks:
  - pause: minutes=1

  - command:  docker exec {{ ansible_hostname }} ceph osd pool set {{ item[1] }} {{ item[0] }} 
    with_nested:
      - [256, 512]
      - ["cephfs_metadata pg_num", "cephfs_data pg_num", "cephfs_metadata pgp_num", "cephfs_data pgp_num"]

  - command:  docker exec {{ ansible_hostname }} ceph -s
    register: result
    until:    result.stdout.find("HEALTH_OK") != -1
    retries:  120
  - debug:    var=result.stdout_lines
